# Pandas

- Some important functions that are used on Pandas to perform analysis on a data frame.

In [1]:
import pandas as pd
import numpy as np

### Initial Look of the Data

- Check the columns
- Check the shape
- Check the dtypes, info, describe

In [3]:
# Read CSV, Excel, SQL
df = pd.read_csv('Sales.csv')
df.head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [4]:
# Look at the DF from the analytical POV
df.columns

Index(['Date', 'Day', 'Month', 'Year', 'Customer_Age', 'Age_Group',
       'Customer_Gender', 'Country', 'State', 'Product_Category',
       'Sub_Category', 'Product', 'Order_Quantity', 'Unit_Cost', 'Unit_Price',
       'Profit', 'Cost', 'Revenue'],
      dtype='object')

In [5]:
df.index

RangeIndex(start=0, stop=113036, step=1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), object(9)
memory usage: 15.5+ MB

In [7]:
df.describe()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000
mean,15.665753,2014.401739,35.919212,11.901660,267.296366,452.938427,285.051665,469.318695,754.370360
std,8.781567,1.272510,11.021936,9.561857,549.835483,922.071219,453.887443,884.866118,1309.094674
min,1.000000,2011.000000,17.000000,1.000000,1.000000,2.000000,-30.000000,1.000000,2.000000
25%,8.000000,2013.000000,28.000000,2.000000,2.000000,5.000000,29.000000,28.000000,63.000000
50%,16.000000,2014.000000,35.000000,10.000000,9.000000,24.000000,101.000000,108.000000,223.000000
75%,23.000000,2016.000000,43.000000,20.000000,42.000000,70.000000,358.000000,432.000000,800.000000
max,31.000000,2016.000000,87.000000,32.000000,2171.000000,3578.000000,15096.000000,42978.000000,58074.000000

In [10]:
df.size

2034648

In [11]:
df.shape

(113036, 18)

In [15]:
print(df.value_counts())

Date        Day  Month     Year  Customer_Age  Age_Group             Customer_Gender  Country        State             Product_Category  Sub_Category       Product                Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  Revenue
2014-03-17  17   March     2014  35            Adults (35-64)        M                Canada         British Columbia  Accessories       Bottles and Cages  Water Bottle - 30 oz.  15              2          5           44      30    74         3
2015-11-24  24   November  2015  41            Adults (35-64)        M                United States  California        Accessories       Tires and Tubes    Patch Kit/8 Patches    8               1          2           8       8     16         3
2016-03-29  29   March     2016  33            Young Adults (25-34)  F                Canada         British Columbia  Accessories       Tires and Tubes    Mountain Tire Tube     24              2          5           71      48    119        3
2015-11-19  19   November  2015  41            Adults (35-64)        M                United States  California        Accessories       Tires and Tubes    Patch Kit/8 Patches    18              1          2           17      18    35         3
2012-11-27  27   November  2012  27            Young Adults (25-34)  M                Canada         British Columbia  Bikes             Road Bikes         Road-650 Red, 44       2               487        783         576     974   1550       3
                                                                                                                                                                                                                                                  ..
2014-02-27  27   February  2014  17            Youth (<25)           M                United States  California        Accessories       Tires and Tubes    Road Tire Tube         22              1          4           64      22    86         1
                                                                                                                                                                                   14              1          4           41      14    55         1
                                                                     F                United States  California        Accessories       Tires and Tubes    Patch Kit/8 Patches    23              1          2           22      23    45         1
2014-02-26  26   February  2014  58            Adults (35-64)        F                United States  Washington        Accessories       Tires and Tubes    Patch Kit/8 Patches    23              1          2           13      23    36         1
2016-07-31  31   July      2016  58            Adults (35-64)        F                Canada         British Columbia  Accessories       Tires and Tubes    Patch Kit/8 Patches    32              1          2           31      32    63         1
Length: 112036, dtype: int64

In [16]:
df.dtypes.value_counts()

object    9
int64     9
dtype: int64

### Slicing, Indexing and Filtering the Data

In [17]:
df.head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [23]:
df[['Day'] + ['Month'] + ['Year']].head()

   Day     Month  Year
0   26  November  2013
1   26  November  2015
2   23     March  2014
3   23     March  2016
4   15       May  2014

In [25]:
df['Total_Cost'] = df['Unit_Cost'] * df['Order_Quantity']
df['Total_Cost'].head()

0     360
1     360
2    1035
3     900
4     180
Name: Total_Cost, dtype: int64

In [30]:
df['Total_Cost'] == df['Cost']

0         True
1         True
2         True
3         True
4         True
          ...
113031    True
113032    True
113033    True
113034    True
113035    True
Length: 113036, dtype: bool

In [38]:
df['Product_Category'].value_counts()

Accessories    70120
Bikes          25982
Clothing       16934
Name: Product_Category, dtype: int64

# loc VS iloc
- **loc**: This lets you select the row by labels 
- **iloc**: This lets you select the row by specifying the integer location.

In [37]:
df.head(2)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,Total_Cost
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950,360
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950,360

In [36]:
(df.loc[df['Year'] == 2015])

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,Total_Cost
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950,360
11,2015-07-30,30,July,2015,32,Young Adults (25-34),F,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,398,360,758,360
13,2015-07-15,15,July,2015,34,Young Adults (25-34),M,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,349,315,664,315
15,2015-08-02,2,August,2015,29,Young Adults (25-34),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,517,315,832,315
17,2015-09-02,2,September,2015,29,Young Adults (25-34),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45,120,74,45,119,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113015,2015-12-10,10,December,2015,20,Youth (<25),F,United States,Washington,Clothing,Vests,"Classic Vest, M",6,24,64,156,144,300,144
113017,2015-10-04,4,October,2015,20,Youth (<25),M,United States,Oregon,Clothing,Vests,"Classic Vest, L",18,24,64,559,432,991,432
113021,2015-10-02,2,October,2015,34,Young Adults (25-34),M,United States,California,Clothing,Vests,"Classic Vest, S",24,24,64,929,576,1505,576
113027,2015-07-08,8,July,2015,29,Young Adults (25-34),M,Germany,Hessen,Clothing,Vests,"Classic Vest, L",21,24,64,746,504,1250,504
113029,2015-12-28,28,December,2015,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",2,24,64,75,48,123,48

In [47]:
# Display all the females from US who bought Bikes in the Year 2015

df.loc[(df['Year'] == 2015 ) & (df['Customer_Gender'] == 'F') & (df['Country'] == 'United States') & (df['Product_Category'] == 'Bikes')]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,Total_Cost
49381,2015-07-18,18,July,2015,20,Youth (<25),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252,2295,997,1252,2249,1252
49383,2015-07-25,25,July,2015,20,Youth (<25),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252,2295,997,1252,2249,1252
49385,2015-12-04,4,December,2015,20,Youth (<25),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252,2295,997,1252,2249,1252
49463,2015-07-13,13,July,2015,22,Youth (<25),F,United States,Washington,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",1,420,769,180,420,600,420
49465,2015-07-16,16,July,2015,22,Youth (<25),F,United States,Washington,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",1,420,769,180,420,600,420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111799,2015-12-25,25,December,2015,29,Young Adults (25-34),F,United States,Oregon,Bikes,Touring Bikes,"Touring-1000 Blue, 50",1,1482,2384,568,1482,2050,1482
111801,2015-12-26,26,December,2015,29,Young Adults (25-34),F,United States,Oregon,Bikes,Touring Bikes,"Touring-1000 Blue, 50",1,1482,2384,568,1482,2050,1482
111973,2015-07-10,10,July,2015,44,Adults (35-64),F,United States,California,Bikes,Touring Bikes,"Touring-3000 Yellow, 62",3,461,742,798,1383,2181,1383
111975,2015-08-25,25,August,2015,44,Adults (35-64),F,United States,California,Bikes,Touring Bikes,"Touring-3000 Yellow, 62",1,461,742,266,461,727,461
111977,2015-08-29,29,August,2015,44,Adults (35-64),F,United States,California,Bikes,Touring Bikes,"Touring-3000 Yellow, 62",1,461,742,266,461,727,461

In [41]:
df.Product_Category.value_counts()

Accessories    70120
Bikes          25982
Clothing       16934
Name: Product_Category, dtype: int64

In [42]:
df.Customer_Gender.value_counts()

M    58312
F    54724
Name: Customer_Gender, dtype: int64

In [43]:
df.Product_Category.value_counts()

Accessories    70120
Bikes          25982
Clothing       16934
Name: Product_Category, dtype: int64

In [ ]:
# Display all the rows till 500

df.iloc[430:50]

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,Total_Cost
430,2014-06-28,28,June,2014,48,Adults (35-64),F,United Kingdom,England,Accessories,Bike Racks,Hitch Rack - 4-Bike,6,45,120,421,270,691,270
431,2016-06-28,28,June,2016,48,Adults (35-64),F,United Kingdom,England,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,281,180,461,180
432,2014-02-26,26,February,2014,24,Youth (<25),M,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,9,45,120,448,405,853,405
433,2016-02-26,26,February,2016,24,Youth (<25),M,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,10,45,120,498,450,948,450
434,2014-07-29,29,July,2014,35,Adults (35-64),M,United Kingdom,England,Accessories,Bike Racks,Hitch Rack - 4-Bike,19,45,120,1334,855,2189,855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2016-04-13,13,April,2016,40,Adults (35-64),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,2,45,120,148,90,238,90
496,2014-04-30,30,April,2014,40,Adults (35-64),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,6,45,120,443,270,713,270
497,2016-04-30,30,April,2016,40,Adults (35-64),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,5,45,120,369,225,594,225
498,2013-10-03,3,October,2013,25,Young Adults (25-34),M,France,Essonne,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,491,315,806,315
499,2015-10-03,3,October,2015,25,Young Adults (25-34),M,France,Essonne,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,491,315,806,315

In [51]:
df.iloc[1]

Date                         2015-11-26
Day                                  26
Month                          November
Year                               2015
Customer_Age                         19
Age_Group                   Youth (<25)
Customer_Gender                       M
Country                          Canada
State                  British Columbia
Product_Category            Accessories
Sub_Category                 Bike Racks
Product             Hitch Rack - 4-Bike
Order_Quantity                        8
Unit_Cost                            45
Unit_Price                          120
Profit                              590
Cost                                360
Revenue                             950
Total_Cost                          360
Name: 1, dtype: object

In [59]:
age_more_than_35 = df[df['Customer_Age'] > 35]
age_more_than_35

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,Total_Cost
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401,1035
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088,900
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418,180
5,2016-05-15,15,May,2016,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,5,45,120,297,225,522,225
6,2014-05-22,22,May,2014,47,Adults (35-64),F,Australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,199,180,379,180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113029,2015-12-28,28,December,2015,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",2,24,64,75,48,123,48
113030,2014-04-12,12,April,2014,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",6,24,64,225,144,369,144
113031,2016-04-12,12,April,2016,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",3,24,64,112,72,184,72
113034,2014-03-04,4,March,2014,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",24,24,64,684,576,1260,576
113035,2016-03-04,4,March,2016,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",23,24,64,655,552,1207,552

### Drop Stuff

- A lot of times you might need to drop unnecessary rows and columns that are not that relevant.

In [61]:
df.drop(columns=['Day', 'Month', 'Year'])
df.drop(columns=['Total_Cost'])

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113031,2016-04-12,12,April,2016,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",3,24,64,112,72,184
113032,2014-04-02,2,April,2014,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113033,2016-04-02,2,April,2016,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113034,2014-03-04,4,March,2014,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",24,24,64,684,576,1260
113035,2016-03-04,4,March,2016,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",23,24,64,655,552,1207